name: Init repo
on: [push]

permissions:
  contents: write  # Enables pushing commits back to repository

jobs:
  rename-project:
    if: ${{ github.repository != 'bcda-aps/bits-starter' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Run init_repo.sh
        run: |
          set -vxeuo pipefail
          bash .github/workflows/init_repo.sh ${{ github.repository }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "✅ Ready to clone and code."
          push_options: --force
